version: 2

sources:
  - name: RAW_DATA # this is the source_name
    database: DBT
    schema: RAW_DATA
    tables:
      - name: products
        columns:
          - name: product_id
            tests:
              - unique
      - name: orders
        columns:
          - name: order_id
            tests:
              - unique              